### ISSUE TITLE
javaparser-core: fails to pattern match records: uplift javaparser-core

### ISSUE THREAD

**Issue by hensan64** [revelc/impsort-maven-plugin#112]
**Describe the bug**
A bug in javaparser-core has been release, but impsort still uses the old.
Parsing using Java 21 should support pattern matching of records.
See https://github.com/javaparser/javaparser/issues/4217

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 1.11.0

**To Reproduce**
See https://github.com/javaparser/javaparser/issues/4217

**Expected behavior**
Parsing using Java 21 should support pattern matching of records.

**Screenshots**
NA

**Additional context**
Just uplift javaparser-core to 3.26.2.

**Comment by hazendaz** [comment]
Will try to get a release out sometime in next week or so unless @ctubbsii has time to get one out sooner.  Typically dependabot will send the PR but its limited time of run here so it would show up on later cycle.  The javaparser update just came out yesterday.

**Comment by hazendaz** [comment]
released 1.12.0 tonight.  will be in central in 30 minutes or so.
