### ISSUE TITLE
impsort-maven-plugin fails to remove unnecessary `import jakarta.validation.constraints.Pattern;` if 'Pattern' text is found in a javadoc comment

### ISSUE THREAD

**Issue by laurent-gougeon** [revelc/impsort-maven-plugin#114]
**Describe the bug**
impsort-maven-plugin fails to remove unnecessary `import jakarta.validation.constraints.Pattern;` if 'Pattern' text is found in a javadoc comment...

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 1.12.0
 - OS: rocky linux 9

**To Reproduce**
1. Use following code snippet in a project:
```
package com.test;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Pattern;

public class TestClass
{

    private String attribute;

    /**
     * Getter for Attribute.
     * 
     * This has a Pattern comment
     * 
     * @return value of attribute
     **/
    @ApiModelProperty(value = "This has a Pattern property as text")
    @JsonProperty("attribute")
    @Valid
    public String getAttribute()
    {
        return attribute;
    }

    /**
     * Setter for field attribute (json : attribute).
     *
     * @param someAttribute
     *            value for attribute
     **/
    public void setAttribute(String someAttribute)
    {
        this.attribute = someAttribute;
    }

    @Override
    public boolean equals(Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        TestClass testClassOther = (TestClass) o;
        return Objects.equals(attribute, testClassOther.attribute);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(attribute);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("class TestClass {\n");

        sb.append("    attribute: ").append(toIndentedString(attribute)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString(Object o)
    {
        if (o == null)
        {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
```

2. use impsort-maven-plugin in a maven build
3. See `import jakarta.validation.constraints.Pattern` not removed

**Expected behavior**
`import jakarta.validation.constraints.Pattern` removed from source.

**Additional context**
Note, eclipse 2023-06 succeeds in removing the import upon save file.

From experimentation, it seems that "**Pattern**" in the getAttribute() javadoc comment might cause the issue.

Non removal of the import then causes a sonar code smell reported : java:S1128

**Comment by ctubbsii** [comment]
The feature to remove unused is a best effort attempt to remove unused imports without doing any actual compiling or processing of the byte code to see which classes are actually used. While the case you're describing is certainly a false positive, it falls within the intended goal of best-effort-without-compiling detection. As such, I do not consider this a bug, and will close this issue. In such cases, you should manually remove the unused import. If you wish to improve upon the best-effort detection, please open a PR with the proposed changes and test cases.
