### ISSUE TITLE
Irrelevant 'throws' javadoc - Eclipse vs Impsort

### ISSUE THREAD

**Issue by blacelle** [revelc/impsort-maven-plugin#19]
I'm not sure this change of behavior is expected.

Given the class:

```java
package bug;

import java.text.ParseException;

public class TextWithThrowJavadoc {

	/**
	 * @throws ParseException
	 */
	public String getSecuritypair() {
		return "text";
	}
}

```

Eclipse will keep the import ParseException as the exception is referred by the throws clause in javadoc. Impsort remove the import since 1.3.1

Is it an expected behavior ? I guess not as I might not want to express a RuntimeException in throws (as some static analysis tools would recommend not to do it), but I would want to keep them in the javadoc.

**Comment by ctubbsii** [comment]
That is not expected, but I haven't seen it. I can try to reproduce. Do you have a simple project which demonstrates this behavior that I can clone?

**Comment by hazendaz** [comment]
How exactly is that a valid javadoc? Wouldn't javadoc linter catch that and tell you to remove it?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ctubbsii** [comment]
It's valid, and quite common with runtime exceptions. In any case, I found the bug, and will implement a workaround shortly.

**Comment by ctubbsii** [comment]
The bug appears to be a change upstream in the parser we use. I tentatively created a fix in #20  that works around it by inspecting the parse output a different way... but it's kind of hackish.

**Comment by blacelle** [comment]
> That is not expected, but I haven't seen it. I can try to reproduce. Do you have a simple project which demonstrates this behavior that I can clone?

Just in case, the original report holds a reproducing code snippet.

**Comment by ctubbsii** [comment]
> > That is not expected, but I haven't seen it. I can try to reproduce. Do you have a simple project which demonstrates this behavior that I can clone?
> 
> Just in case, the original report holds a reproducing code snippet.

I also created a test cases in this plugin's build.
