### ISSUE TITLE
Enhance impsort:check to detect * imports

### ISSUE THREAD

**Issue by rsvoboda** [revelc/impsort-maven-plugin#21]
`*` imports are bad practice from various reasons

`impsort:check` could be enhanced to detect `*` imports

Possibly an option which is not enabled by default but can be enabled when the user wants.

**Comment by ctubbsii** [comment]
It's not a bad idea, but I don't think this is necessary, because checkstyle already can enforce this style ban, and this plugin is not intended to replace or enforce style that is already available in other common tools.
