### ISSUE TITLE
Allow empty line between groupings

### ISSUE THREAD

**Issue by hazendaz** [revelc/impsort-maven-plugin#22]
Currently the impsort maven plugin squashes items together such as:

net.xyz.*
org.apache.*

This conflicts with other plugins such as formatter-maven-plugin that can be configured to break between those.  There seems no such way to do with with impsort right now so it is constantly conflicting with formatting.  Using above example, we need a fix to behave like this.

net.xyz.*

org.apache.*

Where line break is clear.  It doesn't need to become the default but does need to be configurable.  Currently impsort is capable of doing this as it does it with the separation between static imports and normal imports.  However, the problem exists in both.

Using 'mybatis-3' as an example project and simply running impsort directly against it results in over 400 file changes due to simply deleting the present separation.  So really this can be tested against any project but that one makes it more clear there is an issue.

To be clear, we are only talking the outermost left word.  So in my example 'net' and 'org'.  The others do not matter from what I've seen on formatting.

**Comment by ctubbsii** [comment]
@hazendaz I think the configuration you want would be something like:

```xml
<configuration>
  <groups>net.,org.,com.,java.,javax.,*</groups>
</configuration>
```

The comma in the configuration should separate named groups with a blank line.

**Comment by hazendaz** [comment]
I'll get to this in a day or two and let you know.  Thanks for the pointer here.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
@ctubbsii ok - confirmed works.  I think it would be nice though if there was a setting that could cause that without having to add all the group info.  I only care about the first part of the package but I guess others might want to open that up to further separation.  Do you see any value to this?  Far easier than guessing packages on a huge project ;)

**Comment by ctubbsii** [comment]
The use case I designed for was to support explicit placement of specific groups. Use cases such as:

* Put 'java' and 'javax' at the bottom,
* Put own company's imports at the top, and outside dependencies at the bottom, or
* Put project-internal imports at the top, and external dependencies at the bottom.

The use case you describe seems arbitrary... creating groups for the sake of creating groups. I don't personally see much value in this style beyond what you get by merely sorting in one big group (I prefer one group for static, then one group for non-static). It seems entirely aesthetic (you really like newlines?). Given that I'm almost always looking at an IDE or a diff, where the imports sections are collapsed, I don't see much point. (Actually, I wrote the plugin, specifically to make diffs smaller... to keep the imports collapsed more frequently.)

I'm not opposed to supporting the style... it's just not a use case I designed for or anticipated.

**Comment by hazendaz** [comment]
Eclipse formatter options

-> Blank Lines

--> Blank lines within compilation unit

---> Between import groups (value)

This is where it line breaks by default in formatter.  If using impsort with no setup, it conflicts and writes the files when it should not.  This costs extra time for no reason.  If I have both impsort and formatter, it ends up rewriting the files needlessly unless I predefine all groups to get the new line you apply or I simply set formatter to not have the new line.  That is the basis here.  Not arbitrary at all.  I'm pretty sure googles checkstyle rules also denote some of this but would need to reconfirm.

From Eclipse...
![image](https://user-images.githubusercontent.com/975267/73413585-25a38a80-42da-11ea-820b-d7a56bd8f48f.png)

Now that I understand your motivation, I think the better option would be to allow for sorting alphabetically which removes the entire need for adding in the groups.  Plus, secondary option to state the same 'blank line between import groups', would result in the same as formatting.  Thus when things are in sync, no extra formatting would occur, plus using poms at super level wouldn't need to add any details as to the groups involved.

**Comment by ctubbsii** [comment]
It is a non-goal of this plugin to match Eclipse's style options, but it does support many of the style choices that Eclipse's "Organize Imports" feature supports, including the default configuration, whose equivalent configuration in this plugin is:

```xml
<configuration>
  <groups>java.,javax.,org.,com.</groups>
</configuration>
```

**Comment by ctubbsii** [comment]
I've been thinking about this a bit. I think what you want could be done with a new option... something like: `<autogroupWildcardLevel>1</autogroupWildcardLevel>`

This option would default to `0`, but if set to a strictly positive integer, would take all imports that matched on the wildcard `*`, and separate them automatically into groups based on the level.

For example, level 1, would automatically break up the group of imports matching `*` into groups based on the first level in the package name: `org.`, `com.`, etc. These groups would still be sorted, so `com.` would be placed before `edu.` and `.org`.

That way, you could specify explicit groups first, and then autogroup any remaining ones:

```xml
<configuration>
  <groups>java.,javax.,com.mycompany.,*</groups>
  <autogroupWildcardLevel>1</autogroupWildcardLevel>
</configuration>
```

I think this could work for your use case, but it's a terrible name. Any suggestions on a better name?

**Comment by hazendaz** [comment]
Not sure on a better naming...maybe 'groupingLevels'?

**Comment by ctubbsii** [comment]
Hmm, maybe `<autogroupDepth />`?

**Comment by hazendaz** [comment]
I guess this is sorting, so maybe <sortDepth /> ?  Trying to think of what makes most sense to someone looking at it.  No real strong opinion either way.

**Comment by dwalluck** [comment]
I added this plugin to a project the other day and got a similar complaint to the one here. We wanted to follow the default IDEA ordering, so we wanted `javax` before `java`, but also a blank line between them.

I see various options discussed here. Wouldn't it just be easier to allow specifying a blank? For example an empty group name could be rendered as a blank line, like `<groups>javax., , java.</groups>`.

**Comment by ctubbsii** [comment]
@dwalluck My intent is to keep things as simple as possible. When features conflict with simplicity, I want to favor simplicity. Supporting complex import-ordering conventions is not a goal of this project. The goal of this project is to enable automatic ordering of one simple convention within a project, during the build, so that people using different IDEs won't cause merge conflicts and style flip-flopping. I'm willing to include features to support additional styles, within reason... but not at the cost of simplicity.

Adding a special option to either insert a blank line, or omit a blank line, is something I'd be willing to do... but trying to figure how to have a simple configuration that automatically groups is another matter. So, I think we can do something like your suggestion on #28, but the more complicated case of automatic grouping discussed in this issue might need some additional thought.

**Comment by ctubbsii** [comment]
This issue has been open awhile. At this point, I think most people using this plugin are content with its limitations and (hopefully) have realized they don't actually need that much complexity to the ordering of their imports. I suspect most people had that much complexity in their import styling just because that's how they had been doing it, not because they actually require that much complexity. So I'm going to close this for now. If it really becomes a need to add these extra features, we can consider it at a future time. For now, I'd like to keep the plugin relatively simple with limited features and basic styling.
