### ISSUE TITLE
Use an optional stale file detection to avoid parsing all the java files if they have not changed

### ISSUE THREAD

**Issue by gnodet** [revelc/impsort-maven-plugin#25]
I'm investigating using this plugin in [Camel](https://github.com/apache/camel).  I've put a lof of efforts those past months to reduce the build time (and especially when re-building).
I'd like to avoid adding too much time to this build use case, so I'll submit a PR to check the files timestamp and avoid the plugin execution if no source file has changed since last run.

**Comment by gnodet** [comment]
The check was not iterating through subdirs, hence the performance boost.  I'll close this one for now

**Comment by ctubbsii** [comment]
@gnodet For future reference, if you do decide to revisit this, or any other issue. You do not need to create an issue first before you create a PR. You can just create the PR... if they are created at the same time, they are basically redundant, since PRs on GitHub are already handled as issues.
