### ISSUE TITLE
Cache is not invalidated/recalculated on plugin update

### ISSUE THREAD

**Issue by famod** [revelc/impsort-maven-plugin#48]
**Describe the bug**
Cache is not invalidated on plugin update.

**Versions (OS, Maven, Java, and others, as appropriate):**
 - 1.6.0/1.6.1
 - OS: Ubuntu 20
 - Others: Maven 3.8.1, Java 11.0.11 (AdoptOpenJDK)

**To Reproduce**
Steps to reproduce the behavior (or a link to an example repository that reproduces the problem):
1. Optional: Set e.g. `<cachedir>.cache</cachedir>` (outside of target). If you don't do this make sure to _not_ use `mvn clean ...` for obvious reasons.
2. Run the plugin in version 1.6.0 via `mvn`
3. Check file
4. Run the plugin in version 1.6.1 via `mvn`
5. Check file again, it did not change

**Expected behavior**
As plugin updates might alter the sorting result, the plugin version should be taken into account when calculating the hashes.

**Additional context**
I scanned #42 briefly and I couldn't find anything related to the plugin version or the plugin config. I do think that if you change certain config parameters, the cache should be invalidated as well.

I ran into thos problem while trying to reproduce https://github.com/quarkusio/quarkus/pull/17190 locally. Since I already had a cache from a 1.6.0 run, I at first could not reproduce CI behavior.

**Comment by famod** [comment]
This probably also affects the formatter plugin.

**Comment by ctubbsii** [comment]
I don't think I want to change this behavior. See the discussion on formatter-maven-plugin#453 for a discussion on this topic. I would prefer that user's manage their own cache's lifecycle, rather than this plugin try to determine that for them, possibly invalidating the cache when they don't want it to.
