### ISSUE TITLE
Allow ASCII sort order for static imports

### ISSUE THREAD

**Issue by AlejandroBertolo** [revelc/impsort-maven-plugin#56]
Greetings, 
First of all, thanks for your work in this plugin, I've been using it regularly and it's very useful and time saving.

However, I've noticed the static import order is not fully compliant with the [Google Java style](https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing) that our organization wishes to enforce, which is based in [ASCII sort order](http://support.ecisolutions.com/doc-ddms/help/reportsmenu/ascii_sort_order_chart.htm). **This raises some issues when pairing this plugin with certain Checkstyle configurations.**

Basically, according to ASCII Sort order, imports starting with capital letters are expected to be placed first.

Currently, ImpSort sort order returns this:
![non-ascii](https://user-images.githubusercontent.com/60966552/141443490-fff1c042-8666-4981-b634-70cb232e4f1b.PNG)

While Ascii Sort order would produce:
![ascii](https://user-images.githubusercontent.com/60966552/141445695-37cc8ab5-3d89-484c-891b-71d13996563f.PNG)

This results in unavoidable checkstyle violations in projects whose checkstyle sheets include:
`      <property name="sortImportsInGroupAlphabetically" value="true"/>`

**Is there any chance we get a param to toogle Ascii Sort Order?**

Thanks in advance.

**Comment by ctubbsii** [comment]
This feels related to #15 . Have you tried toggling the option introduced there? I'm trying to figure out if this is another edge case or if it is the same issue... because this should have already been sorting using ASCII sort order. It definitely looks like there's something going on with nested inner-classes and/or static imports, where there's likely edge cases.

**Comment by AlejandroBertolo** [comment]
> 
> 
> This feels related to #15 . Have you tried toggling the option introduced there? I'm trying to figure out if this is another edge case or if it is the same issue... because this should have already been sorting using ASCII sort order. It definitely looks like there's something going on with nested inner-classes and/or static imports, where there's likely edge cases.

Hey there, you are right. setting **breadthFirstComparator** to false seems to have enabled ASCII sort order, clearing every related checkstyle violation. It's perhaps not very intuitive, but it does work, so this issue can be closed. Thanks a lot :)!

**Comment by hazendaz** [comment]
as noted as figured out using existing settings, closing.
