### ISSUE TITLE
Change cache to use relative path of the project rather than full path of system

### ISSUE THREAD

**Issue by hazendaz** [revelc/impsort-maven-plugin#58]
**Describe the bug**

The cache works fine but it is listing the full build path.  If not storing the cache in git, this is fine.  However, when storing it in git, the full path is a problem.  This is different than how this is implemented with formatter-maven-plugin.  There is no expectation that every build machine have project in exact same place making sharing a non starter.

**Versions (OS, Maven, Java, and others, as appropriate):**

Confirmed with windows only at the moment but expecting the same on linux.

**To Reproduce**

1. Run a build with impsort, check the impsort-maven-cache.properties in target folder
2. See that it lists the entire path (far more than necessary)

looks like C\:\\xxxx\xxxx\xxxx\\xxxx\\myProject\\src\\main\\java\\somefile.java=XXXX

**Expected behavior**

Expected behaviour is to list the location relative to the pom that ran impsort so this can effectively be applied in git and shared.

Should be content only inside the build folder, using example would only be

\\src\\main\\java\\somefile.java

This will further help speed up processing as less is being written.

Our use case

We have formatting entirely automated so its on both windows and linux platforms.  On linux, we are running in docker nodes through jenkins.  The path changes depending on docker node used.  We also do not enforce every developer use the same space on their machines.  That would be extremely hard to enforce.  We have the formatter plugin doing this now with it auto committing back to the repo without issue via jenkins process running the build so we end up with both windows and linux in the files (develoepr in windows commits on their own as no git hook yet).  We would like to do the same here with impsort but cannot due to this current behaviour.  Once this specific issue is addressed, we also need to remove the timestamp from the file and sort it like was done in formatter-maven-plugin 2.18.0.  That is because some tools like maven plugins will actually keep writing the cache on windows as the hash table enforces no order.  Only mentioning that here for now as this primary issue makes it not possible to go any further.

I'd be happy to work on this given I did the one over in the formatter plugin and with 2.18.0 release its working perfectly for caching.

**Comment by ctubbsii** [comment]
@hazendaz Feel free to submit a PR to change the behavior here. I can review it.

**Comment by hazendaz** [comment]
@ctubbsii Thanks.  I'll try to get something sent for review this coming weekend.

**Comment by hazendaz** [comment]
Resolved via #59
