### ISSUE TITLE
Remove empty line between imports

### ISSUE THREAD

**Issue by hsoehalim** [revelc/impsort-maven-plugin#63]
Hello There,

I'm using Eclipse IDE and i was wondering if there's a way to remove empty line between imports. If i don't use groups, i can still see 1 empty line between static and non-static imports. If I use groups, then i can see 1 empty line between each import groups.

Thanks,
Harry

**Comment by ctubbsii** [comment]
Instructions for this [already exist in the documentation](https://code.revelc.net/impsort-maven-plugin/sort-mojo.html#joinStaticWithNonStatic)

**Comment by hsoehalim** [comment]
"joinStaticWithNonStatic" only resolve the first problem (ie. with out using "groups"). How about if I use "groups"?

**Comment by ctubbsii** [comment]
> "joinStaticWithNonStatic" only resolve the first problem (ie. with out using "groups"). How about if I use "groups"?

A "group", by definition, is isolated from others by blank lines. That is how it is currently intended to work. Extending that concept to allow more robust configuration options is duplicated in #22 and #28.

**Comment by hsoehalim** [comment]
Ah yeah, both #22 <https://github.com/revelc/impsort-maven-plugin/issues/22>
 and #28 <https://github.com/revelc/impsort-maven-plugin/issues/28> have
what I need. Thanks!
