### ISSUE TITLE
impsort-maven-plugin reports unparseable java file when using certain new java features

### ISSUE THREAD

**Issue by reuben-tonna-ixaris** [revelc/impsort-maven-plugin#67]
When using the patterns matching capability for instanceof as per https://docs.oracle.com/en/java/javase/17/language/pattern-matching-instanceof-operator.html the latest 1.8.0 plugin fails to parse the file containing this syntax.

I am using java 17.

As an example, the below fails ...

if (exception instanceof HttpStatusCodeException httpStatusCodeException) {
     do stuff
}

Using the older approach works ..

if (exception instanceof HttpStatusCodeException) {
     HttpStatusCodeException httpStatusCodeException = (HttpStatusCodeException) exception;
     do stuff
}

**Comment by hazendaz** [comment]
hmmm, I'm positive I've personally done this on multiple repos at work without issue.  Can you provide a small reproducible repo that is failing?

**Comment by reuben-tonna-ixaris** [comment]
Attached is a very simple maven based  java application
[impsort-issues.zip](https://github.com/revelc/impsort-maven-plugin/files/10432372/impsort-issues.zip)

Just do mvn clean compile.  I get the following:

[ERROR] Failed to execute goal net.revelc.code:impsort-maven-plugin:1.8.0:sort (sort-imports) on project impsort-issues: Error reading file /tmp/test/java17/impsort-issues/src/main/java/Application.java: file: /tmp/test/java17/impsort-issues/src/main/java/Application.java; reason: the Java file contained parse errors 

If from Application.java I remove the pattern match i.e. use the plain old instanceof check this builds without a problem.

The java version is openjdk 17.0.5 2022-10-18

**Comment by ctubbsii** [comment]
If this bug can be confirmed, the fault will most likely be the upstream javaparser library, as in #54. If upstream fixes the issue in the parser, we can update to that version. One way to help troubleshoot this is to rebuild this plugin using the newest version of the javaparser library, and see if that works on your project. If so, it's a simple pull request to merge and release.

**Comment by reuben-tonna-ixaris** [comment]
Tried with a rebuilt plugin using <javaparser.version>3.24.10</javaparser.version> and the problem is still there.  So the java parser library seems to still not be spec. compliant - will open a bug report in that project.

**Comment by reuben-tonna-ixaris** [comment]
Does not seem to be a problem with the parser however.  I opened a ticket with the above test case in that repo and as per reply on the java parser report ticket thread (https://github.com/javaparser/javaparser/issues/3857) java parser parses without issue.

**Comment by ctubbsii** [comment]
I tested this and it looks like this is simple user error. You did not set the Java language compliance level, as per [the documentation](https://code.revelc.net/impsort-maven-plugin/sort-mojo.html#compliance). By default, it is set to the value of `${maven.compiler.release}`, which you do not have set in your example project. So, you can either set the `<compliance />` option in the config for this plugin, or (better) set the `<maven.compiler.release />` property in your POM's `<properties />`.

**Comment by reuben-tonna-ixaris** [comment]
setting maven.compiler.release to 17 solves the issue as suggested.  Thanks
