### ISSUE TITLE
JavaParser broken with Sequential Collections (jdk 21) and generally jdk 19+

### ISSUE THREAD

**Issue by hazendaz** [revelc/impsort-maven-plugin#79]
Nothing to do here, just noting for others as underlying javaparser is blocking on newer jdks.

At the moment, javaparser has stated won't [fix](https://github.com/javaparser/javaparser/issues/4022) but checking on my [commit](https://github.com/hazendaz/javaparser/commit/146ac1a3c027fcf0bee25e886f2dd89b5fcc4a0d) to see if that might be a path forward.  The issue surfaces if code is targeted to jdk 21 runtime.  If it is targeted earlier it will in fact build up through 17.  Anything higher has issues as blocking due to another issue with enum support locked in javaparser.  I have a fix for that too that stubs that out for them.  I've tested my fixes against this plugin and it works fine.

The issues found there seem to imply it works through java 20 but not exactly.  The enums are needed there for its matching which is a trivial effort.

**Comment by ctubbsii** [comment]
The issue seems to describe a problem building javaparser with JDK 21. Does it also apply to users running the javaparser with JDK 21? If it's only when building javaparser, I don't think there's anything for this project to track.

**Comment by hazendaz** [comment]
Anytime you set the run time target to 21 it will fail with this plugin.  It's not about building javaparser.  That too is a problem but not the one here.  I have code for them that needs applied to open up targets 18 through 21.  Others have also reported same and have been skipping this plugin as I'm now also doing.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by holly-cummins** [comment]
Adding the exact error message, for others who might be seeing this problem:

```
[ERROR] Failed to execute goal net.revelc.code:impsort-maven-plugin:1.9.0:sort (sort-imports) on project <whatever>: Execution sort-imports of goal net.revelc.code:impsort-maven-plugin:1.9.0:sort failed: No enum constant com.github.javaparser.ParserConfiguration.LanguageLevel.JAVA_21 -> [Help 1]
```

**Comment by gunnarmorling** [comment]
If JavaParser is stagnating on a permanent basis, moving to the Eclipse parser might be an alternative? It can be used as a library (the [Forge Roaster](https://github.com/forge/roaster) abstraction might serve as source of inspiration), so it may do the job here.

**Comment by nils-christian** [comment]
Hi,

It would be nice to know some kind of roadmap or plan (or even a workaround) for this. Currently the Impsort plugin is a blocker for us to move towards Java 21.

Thank you and best regards

  Nils

**Comment by hazendaz** [comment]
To be clear, this issue on surfaces when targeting java runtime of 18+ as impsort is released and 19+ if overriding javaparser to latest.  Since this plugin relies on javaparser and javaparser implies enum checks to block newer java usage entirely, there is nothing to do here.  I would suggest just skipping impsort in that case and circling back at some later date.  There should be enough info on the links provided by the author of javaparser to his stance.  This ticket simply served to note that it was attempted to relax those enums up to all java versions (with understanding that new features would not be supported).  However, the author is against that direction at this time.  He is open though to pull requests to bring in proper support but I didn't have time for it.

I would not consider this as a blocker for running a target on newer jvms as its not a critical path to doing so.  Its a bummer not to have but not a show stopper.

**Comment by hazendaz** [comment]
See https://github.com/javaparser/javaparser/pull/4230 for what was needed over there but declined in current form.

**Comment by ctubbsii** [comment]
@hazendaz Will it suffice to trick the impsort by specifying `impsort.compliance=17` and just ignoring the errors that occur after the package declaration, similar to what was proposed in #83? Is that a valid workaround?

**Comment by hazendaz** [comment]
@ctubbsii So if I go this right, the PR would be to ignore parser errors if set so it at least tries to run and compliance level would have to be set to 18 as that is highest current javaparser allows.  Is that the thought?  That would certainly be better than what I've done and turned it off entirely.  Its already pained people at work as they were used to it working its magic and while we are compiling to java 21, we haven't actually written anything that new yet.  So that does sound like a better work around.  Lean on not blowing up the plugin if it cannot parse while at least attempting to allow it to work.  I'll try to see if running it that way as-is causes any problems to current limit of 17 of latest impsort tomorrow and get back with you.

**Comment by hazendaz** [comment]
@ctubbsii Sorry for delay, confirmed switching 'impsort.compliance' to 17 with the current 1.9.0 impsort release with java target of 21 does work without issue where no new java coding style is used.  So as I understand again with the PR that wants to come in, its more on a file by file basis, if that file has newer style it will fail to parse, instead of blowing up it moves on.  So for even fully new used coding style, this would mostly work even with that.  Whereas if we do nothing, the worst case here we blow up the first time we get a class that does not parse.

So I believe...
* We suggest the compliance level set to '18' on next release as we will be on the newer javaparser that handles 18 when users are targeting 19+.
* We do bring in that PR that attempts to not blow up however that needs to be default set for usage.

Doing nothing at all gets
-> No enum constant com.github.javaparser.ParserConfiguration.LanguageLevel.JAVA_21 for my test
-> With compliance at 17, it worked and in one repo I have where only 3 of us work, 7 of our files got updates we were otherwise missing so this is 100% acceptable to me.

It would be great to get this addressed and released this weekend.  Is there anything that you need my help on to progress this or is it pretty well set other than this confirmation?

**Comment by hazendaz** [comment]
Should be resolved by https://github.com/revelc/impsort-maven-plugin/pull/83, closing.
