### ISSUE TITLE
"Use of patterns with instanceof is not supported"

### ISSUE THREAD

**Issue by dmlloyd** [revelc/impsort-maven-plugin#82]
**Describe the bug**

When running the `sort` goal on a Java 17 source file which uses `instanceof` patterns (e.g. `if (obj instanceof Class<?> cl) { ... do something with cl ... }`, we get an error:

```text
(line 27,col 20) Use of patterns with instanceof is not supported.
(line 28,col 20) Use of patterns with instanceof is not supported.
(line 34,col 20) Use of patterns with instanceof is not supported.
(line 35,col 20) Use of patterns with instanceof is not supported.
(line 66,col 13) Use of patterns with instanceof is not supported.
(line 68,col 20) Use of patterns with instanceof is not supported.
(line 70,col 20) Use of patterns with instanceof is not supported.
(line 96,col 13) Use of patterns with instanceof is not supported.
(line 170,col 13) Use of patterns with instanceof is not supported.
(line 173,col 20) Use of patterns with instanceof is not supported.
(line 163,col 17) Use of patterns with instanceof is not supported.
(line 172,col 21) Use of patterns with instanceof is not supported.
(line 35,col 16) Use of patterns with instanceof is not supported.
(line 37,col 13) Use of patterns with instanceof is not supported.
```

**Versions (OS, Maven, Java, and others, as appropriate):**
 - Affected version(s) of this project: 1.9.0
 - OS: any
 - Others: JDK 17+ 

**To Reproduce**
Configure the plugin on a project using this syntax.

**Additional context**
The bug is likely due to misconfiguring `javaparser`. It should be configured to use the same JDK version that is used to compile the project (from the complier plugin), but is likely instead being configured to use the static instance or otherwise is not being configured with the correct source version.

See https://stackoverflow.com/questions/77117816/javaparser-lib-issue-parseproblemexception-use-of-patterns-with-instanceof-is for more context.

**Comment by dmlloyd** [comment]
A secondary issue is that the error message isn't reporting the file name, just line and column numbers. But that's relatively minor as we don't normally expect errors at this stage.

**Comment by dmlloyd** [comment]
Likely the same cause as #79.

**Comment by delanym** [comment]
This should be reopened.
I'm getting `(line 40,col 11) Use of patterns with instanceof is not supported.` for the code 

```java
  @Override
  public boolean equals(Object o) {
    if (!(o instanceof Command c)) {          // line 40
      return false;
    }
    if (command != c.getCommand()) {
      return false;
    }
    if (!source.equals(c.getSource())) {
      return false;
    }
    return destination.equals(c.getDestination());
  }
```

The pattern variable `c` is in scope outside the first if.
This compiles with `java-1.22.0-openjdk-amd64`.

I don't know why this should be a problem for `net.revelc.code:impsort-maven-plugin:1.9.0` and not `net.revelc.code.formatter:formatter-maven-plugin:2.23.0`

**Comment by dmlloyd** [comment]
Did you set the `compliance` configuration to the appropriate Java version?

**Comment by delanym** [comment]
Thanks, that's it. I've got a source and a target but not a release.
I should probably set compiler-plugin to use this as well.
