### ISSUE TITLE
Allow static imports mixed with non-static

### ISSUE THREAD

**Issue by a14n** [revelc/impsort-maven-plugin#9]
At work we have the following eclipse import rules:

```
#Organize Import Order
#Fri Mar 16 10:43:04 CET 2012
17=\#
16=
15=\#javax
14=javax
13=\#java
12=java
11=\#groovy
10=groovy
9=\#org
8=org
7=\#net
6=net
5=\#junit
4=junit
3=\#com
2=com
1=\#com.corp
0=com.corp
```

There doesn't seem to have a way to configure the `impsort-maven-plugin` to have static group between 2 non-static.

WDYT about the best way to handle that ?

**Comment by ctubbsii** [comment]
My first thought is somewhat judgmental... as in: "that's a terrible style". Honestly, I've never seen anything like this before, and I can't imagine what advantage such a style could possibly have. :smiley_cat: 

However, I think this may be possible with some tweaks to the plugin (it's not currently possible, of course). I'd have to put some thought into what those tweaks would look like. I'd like to keep the plugin as simple as possible. I don't suppose you could convince your workplace to adopt a simpler style? :wink:

**Comment by a14n** [comment]
>I don't suppose you could convince your workplace to adopt a simpler style?

I guess it's possible but as Eclipse and IntelliJ allow such styles I may not be the only one to use something like that.

FWIW there's also an issue to handle such style in checkstyle. See https://github.com/checkstyle/checkstyle/issues/5460

**Comment by ctubbsii** [comment]
> I guess it's possible but as Eclipse and IntelliJ allow such styles I may not be the only one to use something like that.

I will convince everybody to change! (j/k) :smiley_cat: 

Seriously, though, do you have a suggestion for how the configuration for this plugin should look to the user, without complicating the current configuration?

**Comment by ctubbsii** [comment]
BTW, one of the goals I had with the simplicity of the configuration, is I wanted to be able to override the config on the command-line easily with `-Dimpsort.groups=...` and `-Dimpsort.staticGroups=...`; that's the reason I didn't have a more complicated configuration, as in something like:

```xml
<configuration>
  <groups>
    <group>
      <prefix>org.</prefix>
      <includeStatic>true</includeStatic>
      <includeNonStatic>false</includeNonStatic>
    </group>
    <group>
      <prefix />
      <includeStatic>true</includeStatic>
      <includeNonStatic>true</includeNonStatic>
    </group>
    ...
  </groups>
</configuration>
```

**Comment by a14n** [comment]
I don't know what's the best way to handle all configs.

Even if it's not obvious at first I quite like your last proposition as it allows every patterns :D (except `#BLANK#` that visually conflict with static imports - perhaps `_` or ` ` or nothing instead : `#org.,_,#com.,_,#*,_,org.,_,com.,_,*` or `#org., ,#com., ,#*, ,org., ,com., ,*` or `#org.,,#com.,,#*,,org.,,com.,,*`)

**Comment by ctubbsii** [comment]
Well, it allows every "prefix" style pattern... next request will probably be something like "support regexes!" or "support reverse alphabetical ordering!" or "support length-based ordering!" or "ignore dots when comparing!" :smiley_cat:

**Comment by ctubbsii** [comment]
Maybe we can support this as "advancedGroups" or some similar name.

**Comment by a14n** [comment]
An other option could be to accept a config file similarily to what is done with https://code.revelc.net/formatter-maven-plugin/validate-mojo.html#configFile (a `*.importorder` file used by eclipse - don't know if IDEA has something similar)

FWIW I managed to change my company rule about imports's order and not really need this feature anymore.

**Comment by ctubbsii** [comment]
> An other option could be to accept a config file ...

That could work, but I don't know that I'd want to use the Eclipse configuration file format without using the Eclipse code... that feature might be more appropriate in the formatter-maven-plugin (which could obsolete this plugin at some point).

For now, I think the "advancedGroups" or similar is worth proceeding with. I'll try adding something like that when I get some spare time.

> FWIW I managed to change my company rule about imports's order and not really need this feature anymore.

LOL. Awesome!

**Comment by ctubbsii** [comment]
Closing this issue for now, as there's nobody championing it any more, and it doesn't seem to be needed. :smiley_cat:
